### ISSUE TITLE
Pod Install gives "NoMethodError - undefined method `files' for #"

### ISSUE THREAD

**Issue by DeArchiTech** [box/box-ios-sdk#285]
Hello there

I am trying to add the SDK to an existing project.
I realized that whenever I tried to do pod install, cocoapods is giving me a no method error, I tried many different solutions and still no luck :( Help would be appreciated!

```
Analyzing dependencies
Downloading dependencies
Using box-ios-sdk (1.0.14)
Generating Pods project
Integrating client project

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/Davix/.rbenv/versions/2.0.0-p353/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.2.0.beta.1
        Ruby : ruby 2.0.0p353 (2013-11-22 revision 43784) [x86_64-darwin15.3.0]
    RubyGems : 2.6.4
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /Users/Davix/.rbenv/versions/2.0.0-p353/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ ae978c13bb3dfeeb0ad9ffd3347b375073c61976
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!
workspace 'MyWorkspace'

target 'IBMCaptureSDK-Sample' do
pod 'box-ios-sdk'
end
```

### Error

```
NoMethodError - undefined method `files' for #<Xcodeproj::Project::Object::PBXFileReference:0x007fe66b84bb20>
/Users/Davix/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:93:in `block in add_pods_library'
/Users/Davix/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:88:in `each'
/Users/Davix/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:88:in `add_pods_library'
/Users/Davix/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:60:in `block in integrate!'
/Users/Davix/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/Davix/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:57:in `integrate!'
/Users/Davix/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/user_project_integrator.rb:129:in `each'
/Users/Davix/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/user_project_integrator.rb:129:in `integrate_user_targets'
/Users/Davix/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/user_project_integrator.rb:63:in `integrate!'
/Users/Davix/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer.rb:612:in `block in integrate_user_project'
/Users/Davix/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/Davix/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer.rb:609:in `integrate_user_project'
/Users/Davix/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer.rb:117:in `install!'
/Users/Davix/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/command/install.rb:37:in `run'
/Users/Davix/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/Davix/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/command.rb:50:in `run'
/Users/Davix/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/cocoapods-1.2.0.beta.1/bin/pod:55:in `<top (required)>'
/Users/Davix/.rbenv/versions/2.0.0-p353/bin/pod:22:in `load'
/Users/Davix/.rbenv/versions/2.0.0-p353/bin/pod:22:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

```

**Comment by crousselle** [comment]
Hi @noobiehacker !
Thank you for using our SDK and reporting issues, it's the only way to make it super easy to use for all developpers.
I'll investigate this issue and come back to you but from what I gather with your description, it looks like it is a cocoapods issue and not related to our pod. Have you tried to setup this project with a different pod by any chance ?

**Comment by DeArchiTech** [comment]
Hey @crousselle 

With further investigations, I guess you are correct.  I asked on the Cocoapod github page and we found a work around for it, so I guess we are good for now.

https://github.com/CocoaPods/CocoaPods/issues/6320

Thank you and I will close this issue for now

David
